/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>

#include "decimal.h"
#define CONVERTATION_FAULT 1
START_TEST(test_is_less) {
  decimal a = {{0, 0, 0, 0}};
  decimal b = {{4294967295, 0, 0, 0}};
  decimal c = {{0, 0, 0, 0}};
  decimal d = {{1, 0, 0, 2147483648}};  // -1
  decimal e = {{1, 0, 0, 2149318656}};  // -1e28
  decimal f = {{1, 0, 0, 1835008}};     // 1e28
  decimal g = {{4294967295, 4294967295, 4294967295, 0}};
  decimal h = {{4294967294, 4294967295, 4294967295, 2147483649}};
  decimal i = {{4294967294, 4294967295, 4294967295, 2147483648}};
  decimal j = {{4294967294, 4294967295, 4294967295, 1835008}};
  decimal k = {{0, 0, 0, 1900544}};
  decimal l = {{1, 0, 0, 1}};
  decimal m = {{1, 0, 0, 65535}};
  decimal n = {{1, 0, 0, 2164260864}};
  decimal o = {{0, 4294967295, 0, 0}};
  decimal p = {{0, 4294967295, 1, 0}};
  decimal q = {{10, 0, 0, 2147483648}};  // -10
  decimal r = {{10, 0, 0, 2147680256}};  // -0,1
  decimal s = {{0, 10, 0, 2147483648}};
  decimal t = {{0, 10, 0, 2147483648}};
  decimal u = {{0, 1, 0, 0}};
  decimal v = {{10, 1, 0, 2147483648}};
  decimal w = {{0, 0, 10, 0}};
  decimal x = {{0, 0, 10, 2147483648}};
  decimal aa = {{1000, 0, 0, 196608}};  // 1000*е-3
  decimal bb = {{100, 0, 0, 131072}};   // 100*е-2
  decimal cc = {{100, 0, 0, 0}};
  decimal dd = {{4294967294, 4294967295, 4294967295, 0}};

  ck_assert_int_eq(1, is_less(a, b));
  ck_assert_int_eq(0, is_less(a, c));
  ck_assert_int_eq(0, is_less(a, d));
  ck_assert_int_eq(0, is_less(a, e));
  ck_assert_int_eq(1, is_less(a, f));
  ck_assert_int_eq(1, is_less(a, g));
  ck_assert_int_eq(0, is_less(a, h));
  ck_assert_int_eq(0, is_less(a, i));
  ck_assert_int_eq(1, is_less(a, j));
  ck_assert_int_eq(1, is_less(i, j));
  ck_assert_int_eq(1, is_less(f, j));
  ck_assert_int_eq(0, is_less(a, k));
  ck_assert_int_eq(0, is_less(a, l));
  ck_assert_int_eq(0, is_less(a, m));
  ck_assert_int_eq(0, is_less(a, n));
  ck_assert_int_eq(1, is_less(b, o));
  ck_assert_int_eq(1, is_less(o, p));
  ck_assert_int_eq(1, is_less(q, d));
  ck_assert_int_eq(0, is_less(d, q));
  ck_assert_int_eq(1, is_less(q, r));
  ck_assert_int_eq(0, is_less(r, q));
  ck_assert_int_eq(1, is_less(s, q));
  ck_assert_int_eq(1, is_less(s, r));
  ck_assert_int_eq(1, is_less(q, a));
  ck_assert_int_eq(0, is_less(s, t));
  ck_assert_int_eq(1, is_less(c, u));
  ck_assert_int_eq(0, is_less(u, c));
  ck_assert_int_eq(1, is_less(v, q));
  ck_assert_int_eq(0, is_less(q, v));
  ck_assert_int_eq(1, is_less(u, w));
  ck_assert_int_eq(0, is_less(w, u));
  ck_assert_int_eq(1, is_less(x, v));
  ck_assert_int_eq(0, is_less(v, x));
  ck_assert_int_eq(0, is_less(aa, bb));
  ck_assert_int_eq(1, is_less(bb, cc));
  ck_assert_int_eq(1, is_less(j, dd));
  ck_assert_int_eq(1, is_less(i, dd));
}
END_TEST

START_TEST(test_is_equal) {
  decimal a = {{0, 0, 0, 0}};
  decimal b = {{0, 0, 0, 0}};
  decimal aa = {{1000, 0, 0, 196608}};  // 1000*е-3
  decimal bb = {{100, 0, 0, 131072}};   // 100*е-2
  decimal h = {{4294967294, 4294967295, 4294967295, 2147483648}};
  decimal i = {{4294967294, 4294967295, 4294967295, 2147483648}};
  decimal g = {{4294967295, 4294967295, 4294967295, 0}};
  decimal j = {{4294967294, 4294967295, 4294967295, 1835008}};
  decimal cc = {{0, 10, 0, 65536}};    // 4294967296 * 10 * e-1
  decimal ee = {{0, 1, 0, 0}};         // 4294967296
  decimal ff = {{0, 100, 0, 131072}};  // 4294967296 * 100 *e-2

  decimal gg = {{0, 0, 1000, 196608}};
  decimal hh = {{0, 0, 1, 0}};

  decimal jj = {{4294967294, 0, 0, 2147483648}};
  decimal kk = {{4294967294, 0, 0, 2147483649}};

  decimal ll = {{10, 0, 0, 1900544}};  // степень 29
  decimal mm = {{10, 0, 0, 1900544}};

  decimal nn = {{10, 0, 0, 2155872256}};  // бит в 23 индексе
  decimal oo = {{10, 0, 0, 2155872256}};

  decimal pp = {{1, 0, 0, 2147483648}};     // -1
  decimal qq = {{1000, 0, 0, 2147680256}};  // -1000e-3

  decimal rr = {{10, 0, 0, 196608}};
  decimal ss = {{9, 0, 0, 196608}};
  decimal tt = {{9, 1, 0, 196608}};

  ck_assert_int_eq(1, is_equal(a, b));
  ck_assert_int_eq(1, is_equal(aa, bb));
  ck_assert_int_eq(1, is_equal(h, i));
  ck_assert_int_eq(0, is_equal(g, i));
  ck_assert_int_eq(0, is_equal(h, j));
  ck_assert_int_eq(1, is_equal(cc, ee));
  ck_assert_int_eq(1, is_equal(cc, ff));
  ck_assert_int_eq(1, is_equal(hh, gg));
  ck_assert_int_eq(0, is_equal(jj, kk));
  ck_assert_int_eq(0, is_equal(ll, mm));
  ck_assert_int_eq(0, is_equal(nn, oo));
  ck_assert_int_eq(1, is_equal(pp, qq));
  ck_assert_int_eq(0, is_equal(rr, ss));
  ck_assert_int_eq(0, is_equal(ss, tt));
}
END_TEST

START_TEST(test_is_less_or_equal) {
  decimal a = {{0, 0, 0, 0}};
  decimal b = {{0, 0, 0, 0}};
  decimal c = {{1, 0, 0, 0}};
  decimal d = {{1, 0, 0, 2147483648}};  // -1
  decimal e = {{1, 0, 0, 2149318656}};  // -1e28
  decimal f = {{4294967294, 4294967295, 4294967295, 1835008}};
  decimal g = {{4294967294, 4294967295, 4294967295, 2149318656}};
  decimal h = {{4294967293, 4294967295, 4294967295, 2149318656}};
  decimal ll = {{10, 0, 0, 1900544}};  // степень 29
  decimal mm = {{10, 0, 0, 1900544}};

  ck_assert_int_eq(1, is_less_or_equal(a, b));
  ck_assert_int_eq(1, is_less_or_equal(b, c));
  ck_assert_int_eq(1, is_less_or_equal(d, a));
  ck_assert_int_eq(1, is_less_or_equal(d, e));
  ck_assert_int_eq(1, is_less_or_equal(e, f));
  ck_assert_int_eq(1, is_less_or_equal(g, h));
  ck_assert_int_eq(0, is_less_or_equal(h, g));
  ck_assert_int_eq(0, is_less_or_equal(ll, mm));
}
END_TEST

START_TEST(test_is_greater) {
  decimal a = {{0, 0, 0, 0}};
  decimal b = {{4294967295, 0, 0, 0}};
  decimal c = {{0, 0, 0, 0}};
  decimal d = {{1, 0, 0, 2147483648}};  // -1
  decimal e = {{1, 0, 0, 2149318656}};  // -1e28
  decimal f = {{1, 0, 0, 1835008}};     // 1e28
  decimal g = {{4294967295, 4294967295, 4294967295, 0}};
  decimal h = {{4294967294, 4294967295, 4294967295, 2147483649}};
  decimal i = {{4294967294, 4294967295, 4294967295, 2147483648}};
  decimal j = {{4294967294, 4294967295, 4294967295, 1835008}};
  decimal k = {{0, 0, 0, 1900544}};
  decimal l = {{1, 0, 0, 1}};
  decimal m = {{1, 0, 0, 65535}};
  decimal n = {{1, 0, 0, 2164260864}};
  decimal o = {{0, 4294967295, 0, 0}};
  decimal p = {{0, 4294967295, 1, 0}};
  decimal q = {{10, 0, 0, 2147483648}};  // -10
  decimal r = {{10, 0, 0, 2147680256}};  // -0,1
  decimal s = {{0, 10, 0, 2147483648}};
  decimal t = {{0, 10, 0, 2147483648}};
  decimal u = {{0, 1, 0, 0}};
  decimal v = {{10, 1, 0, 2147483648}};

  decimal aa = {{1000, 0, 0, 196608}};  // 1000*е-3
  decimal bb = {{100, 0, 0, 131072}};   // 100*е-2
  decimal cc = {{100, 0, 0, 0}};
  decimal dd = {{4294967294, 4294967295, 4294967295, 0}};

  ck_assert_int_eq(0, is_greater(a, b));
  ck_assert_int_eq(0, is_greater(a, c));
  ck_assert_int_eq(1, is_greater(a, d));
  ck_assert_int_eq(1, is_greater(a, e));
  ck_assert_int_eq(0, is_greater(a, f));
  ck_assert_int_eq(1, is_greater(f, a));
  ck_assert_int_eq(0, is_greater(a, g));
  ck_assert_int_eq(0, is_greater(a, h));
  ck_assert_int_eq(1, is_greater(a, i));
  ck_assert_int_eq(1, is_greater(j, a));
  ck_assert_int_eq(0, is_greater(a, j));
  ck_assert_int_eq(1, is_greater(j, i));
  ck_assert_int_eq(1, is_greater(j, f));
  ck_assert_int_eq(0, is_greater(f, j));
  ck_assert_int_eq(0, is_greater(a, k));
  ck_assert_int_eq(0, is_greater(a, l));
  ck_assert_int_eq(0, is_greater(m, a));
  ck_assert_int_eq(0, is_greater(a, n));
  ck_assert_int_eq(1, is_greater(o, b));
  ck_assert_int_eq(0, is_greater(b, o));
  ck_assert_int_eq(1, is_greater(p, o));
  ck_assert_int_eq(0, is_greater(o, p));
  ck_assert_int_eq(1, is_greater(d, q));
  ck_assert_int_eq(0, is_greater(q, d));
  ck_assert_int_eq(1, is_greater(r, q));
  ck_assert_int_eq(1, is_greater(q, s));
  ck_assert_int_eq(1, is_greater(r, s));
  ck_assert_int_eq(1, is_greater(a, q));
  ck_assert_int_eq(0, is_greater(s, t));
  ck_assert_int_eq(1, is_greater(u, c));
  ck_assert_int_eq(0, is_greater(c, u));
  ck_assert_int_eq(1, is_greater(q, v));
  ck_assert_int_eq(0, is_greater(v, q));

  ck_assert_int_eq(0, is_greater(aa, bb));
  ck_assert_int_eq(0, is_greater(bb, aa));
  ck_assert_int_eq(1, is_greater(cc, bb));
  ck_assert_int_eq(1, is_greater(dd, j));
  ck_assert_int_eq(0, is_greater(j, dd));
  ck_assert_int_eq(1, is_greater(dd, i));
}
END_TEST

START_TEST(test_is_greater_or_equal) {
  decimal a = {{0, 0, 0, 0}};
  decimal b = {{4294967295, 0, 0, 0}};
  decimal c = {{0, 0, 0, 0}};
  decimal d = {{1, 0, 0, 2147483648}};   // -1
  decimal e = {{10, 0, 0, 2147483648}};  // -10
  decimal f = {{10, 0, 0, 2147483648}};  // -10
  decimal g = {{1, 0, 0, 2149318656}};   // -1e28
  decimal h = {{1, 0, 0, 1835008}};      // 1e28
  decimal i = {{4294967295, 4294967295, 4294967295, 0}};
  decimal j = {{4294967294, 4294967295, 4294967295, 2149318656}};
  decimal k = {{4294967294, 4294967295, 4294967295, 2149318656}};

  decimal aa = {{1000, 0, 0, 196608}};  // 1000*е-3
  decimal bb = {{100, 0, 0, 131072}};   // 100*е-2
  decimal cc = {{0, 10, 0, 65536}};     // 4294967296 * 10 * e-1
  decimal ee = {{0, 1, 0, 0}};          // 4294967296
  decimal ff = {{0, 100, 0, 131072}};   // 4294967296 * 100 *e-2
  decimal ll = {{10, 0, 0, 1900544}};   // степень 29
  decimal mm = {{10, 0, 0, 1900544}};

  ck_assert_int_eq(0, is_greater_or_equal(a, b));
  ck_assert_int_eq(1, is_greater_or_equal(b, a));
  ck_assert_int_eq(1, is_greater_or_equal(a, c));
  ck_assert_int_eq(1, is_greater_or_equal(d, e));
  ck_assert_int_eq(1, is_greater_or_equal(e, f));
  ck_assert_int_eq(1, is_greater_or_equal(a, g));
  ck_assert_int_eq(0, is_greater_or_equal(a, h));
  ck_assert_int_eq(1, is_greater_or_equal(h, a));

  ck_assert_int_eq(1, is_greater_or_equal(i, a));
  ck_assert_int_eq(0, is_greater_or_equal(a, i));
  ck_assert_int_eq(1, is_greater_or_equal(j, k));

  ck_assert_int_eq(1, is_greater_or_equal(aa, bb));
  ck_assert_int_eq(1, is_greater_or_equal(bb, aa));
  ck_assert_int_eq(1, is_greater_or_equal(cc, ee));
  ck_assert_int_eq(1, is_greater_or_equal(cc, ff));
  ck_assert_int_eq(1, is_greater_or_equal(ee, ff));
  ck_assert_int_eq(0, is_greater_or_equal(ll, mm));
  ck_assert_int_eq(0, is_greater_or_equal(mm, ll));
}
END_TEST

START_TEST(test_is_not_equal) {
  decimal aa = {{1000, 0, 0, 196608}};  // 1000*е-3
  decimal bb = {{100, 0, 0, 131072}};   // 100*е-2
  decimal cc = {{0, 10, 0, 65536}};     // 4294967296 * 10 * e-1
  decimal ee = {{0, 1, 0, 0}};          // 4294967296
  decimal ff = {{0, 100, 0, 131072}};   // 4294967296 * 100 *e-2

  decimal a = {{0, 0, 0, 0}};
  decimal b = {{1, 0, 0, 0}};
  decimal c = {{0, 0, 0, 0}};
  decimal d = {{1, 1, 1, 0}};
  decimal e = {{1, 1, 1, 0}};
  decimal f = {{1, 1, 1, 1}};
  decimal g = {{0, 0, 0, 0}};
  decimal i = {{4294967295, 4294967295, 4294967295, 0}};
  decimal j = {{4294967295, 4294967295, 4294967295, 0}};

  ck_assert_int_eq(0, is_not_equal(aa, bb));
  ck_assert_int_eq(0, is_not_equal(cc, ee));
  ck_assert_int_eq(0, is_not_equal(ee, ff));
  ck_assert_int_eq(0, is_not_equal(cc, ff));
  ck_assert_int_eq(0, is_not_equal(i, j));
  ck_assert_int_eq(0, is_not_equal(a, c));
  ck_assert_int_eq(0, is_not_equal(c, a));
  ck_assert_int_eq(1, is_not_equal(a, b));
  ck_assert_int_eq(1, is_not_equal(b, a));
  ck_assert_int_eq(0, is_not_equal(d, e));
  ck_assert_int_eq(0, is_not_equal(f, e));
  ck_assert_int_eq(0, is_not_equal(a, g));
}
END_TEST

START_TEST(test_from_float_to_decimal) {
  float f = 12.123456;
  float ff = 1.0 / 0.0;
  float fff = 0.0 / 0.0;
  float ffff = -1.0 / 0.0;
  float f_b = -12.2;
  float f_c = 79228162514264337593543950336.0;
  float f_d = 1e-28;
  float f_g = 1.500000000001;
  float f_i = 7922816251426433759354395033.0;
  float f_j = 7922816951426433759354395033.0;
  float f_k = -7922816951426433759354395033.0;
  float f_l = 7.922816e28;
  float f_m = 1e-27;
  float f_n = 1e-29;

  decimal a = {{0, 0, 0, 0}};

  ck_assert_int_eq(1, from_float_to_decimal(ff, &a));
  ck_assert_int_eq(1, from_float_to_decimal(fff, &a));
  ck_assert_int_eq(1, from_float_to_decimal(ffff, &a));

  ck_assert_int_eq(0, from_float_to_decimal(f, &a));
  ck_assert_int_eq(a.bits[0], 1212346);
  ck_assert_int_eq(a.bits[1], 0);
  ck_assert_int_eq(a.bits[2], 0);
  ck_assert_int_eq(a.bits[3], 327680);

  ck_assert_int_eq(0, from_float_to_decimal(f_b, &a));
  ck_assert_int_eq(a.bits[0], 1220000);
  ck_assert_int_eq(a.bits[1], 0);
  ck_assert_int_eq(a.bits[2], 0);
  ck_assert_int_eq(a.bits[3], 2147811328);

  ck_assert_int_eq(1, from_float_to_decimal(f_c, &a));
  ck_assert_int_eq(0, from_float_to_decimal(f_d, &a));
  ck_assert_int_eq(a.bits[0], 0);
  ck_assert_int_eq(a.bits[1], 0);
  ck_assert_int_eq(a.bits[2], 0);
  ck_assert_int_eq(a.bits[3], 393216);

  ck_assert_int_eq(0, from_float_to_decimal(f_l, &a));
  ck_assert_int_eq(a.bits[0], 7922816);
  ck_assert_int_eq(a.bits[1], 0);
  ck_assert_int_eq(a.bits[2], 0);
  ck_assert_int_eq(a.bits[3], 0);

  ck_assert_int_eq(0, from_float_to_decimal(f_g, &a));

  ck_assert_int_eq(a.bits[0], 1500000);
  ck_assert_int_eq(a.bits[1], 0);
  ck_assert_int_eq(a.bits[2], 0);
  ck_assert_int_eq(a.bits[3], 393216);

  ck_assert_int_eq(0, from_float_to_decimal(f_i, &a));
  ck_assert_int_eq(a.bits[0], 7922816);
  ck_assert_int_eq(a.bits[1], 0);
  ck_assert_int_eq(a.bits[2], 0);
  ck_assert_int_eq(a.bits[3], 0);

  ck_assert_int_eq(0, from_float_to_decimal(f_j, &a));
  ck_assert_int_eq(a.bits[0], 7922817);
  ck_assert_int_eq(a.bits[1], 0);
  ck_assert_int_eq(a.bits[2], 0);
  ck_assert_int_eq(a.bits[3], 0);

  ck_assert_int_eq(0, from_float_to_decimal(f_k, &a));
  ck_assert_int_eq(a.bits[0], 7922817);
  ck_assert_int_eq(a.bits[1], 0);
  ck_assert_int_eq(a.bits[2], 0);
  ck_assert_int_eq(a.bits[3], 2147483648);

  ck_assert_int_eq(0, from_float_to_decimal(f_m, &a));
  ck_assert_int_eq(a.bits[0], 0);
  ck_assert_int_eq(a.bits[1], 0);
  ck_assert_int_eq(a.bits[2], 0);
  ck_assert_int_eq(a.bits[3], 393216);
  ck_assert_int_eq(1, from_float_to_decimal(f_n, &a));
}
END_TEST

START_TEST(test_from_decimal_to_float) {
  decimal a = {{4294967295, 4294967295, 4294967295, 0}};
  decimal b = {{4294967295, 4294967295, 4294967295, 1835008}};
  decimal c = {{4294967295, 4294967295, 4294967295, 2149318656}};
  float x = 0.0;
  float *y = NULL;

  ck_assert_int_eq(0, from_decimal_to_float(a, &x));

  ck_assert_int_eq(0, from_decimal_to_float(b, &x));
  ck_assert_float_eq_tol(x, 7.92282, 1e-5);

  ck_assert_int_eq(0, from_decimal_to_float(c, &x));
  ck_assert_float_eq_tol(x, -7.92282, 1e-5);

  ck_assert_int_eq(1, from_decimal_to_float(c, y));
}
END_TEST

START_TEST(test_from_int_to_decimal) {
  int a = 0;
  int b = 1;
  int c = -1;
  int d = 2147483647;
  int f = -2147483648;

  decimal dec = {{0, 0, 0, 0}};
  decimal *m = NULL;

  ck_assert_int_eq(0, from_int_to_decimal(a, &dec));
  ck_assert_int_eq(a, dec.bits[0]);
  ck_assert_int_eq(0, dec.bits[1]);
  ck_assert_int_eq(0, dec.bits[2]);
  ck_assert_int_eq(0, dec.bits[3]);

  ck_assert_int_eq(0, from_int_to_decimal(b, &dec));
  ck_assert_int_eq(b, dec.bits[0]);
  ck_assert_int_eq(0, dec.bits[1]);
  ck_assert_int_eq(0, dec.bits[2]);
  ck_assert_int_eq(0, dec.bits[3]);

  ck_assert_int_eq(0, from_int_to_decimal(c, &dec));
  ck_assert_int_eq(-c, dec.bits[0]);
  ck_assert_int_eq(0, dec.bits[1]);
  ck_assert_int_eq(0, dec.bits[2]);
  ck_assert_int_eq(2147483648, dec.bits[3]);

  ck_assert_int_eq(0, from_int_to_decimal(d, &dec));
  ck_assert_int_eq(d, dec.bits[0]);
  ck_assert_int_eq(0, dec.bits[1]);
  ck_assert_int_eq(0, dec.bits[2]);
  ck_assert_int_eq(0, dec.bits[3]);

  ck_assert_int_eq(0, from_int_to_decimal(f, &dec));
  ck_assert_uint_eq(2147483648, dec.bits[0]);
  ck_assert_int_eq(0, dec.bits[1]);
  ck_assert_int_eq(0, dec.bits[2]);
  ck_assert_int_eq(2147483648, dec.bits[3]);

  ck_assert_int_eq(1, from_int_to_decimal(a, m));
}
END_TEST

START_TEST(test_from_decimal_to_int) {
  decimal a = {{0, 1, 0, 0}};
  decimal b = {{1, 0, 0, 1900544}};
  decimal c = {{0, 0, 1, 0}};
  decimal d = {{2147483648, 0, 0, 0}};
  decimal e = {{2147483649, 0, 0, 2147483648}};
  decimal f = {{2147483648, 0, 0, 2147483648}};
  decimal g = {{2147483647, 0, 0, 0}};
  decimal h = {{112, 0, 0, 65536}};
  decimal i = {{112, 0, 0, 2147549184}};
  int m = 0;

  ck_assert_int_eq(1, from_decimal_to_int(a, &m));
  ck_assert_int_eq(1, from_decimal_to_int(b, &m));
  ck_assert_int_eq(1, from_decimal_to_int(c, &m));
  ck_assert_int_eq(1, from_decimal_to_int(d, &m));
  ck_assert_int_eq(1, from_decimal_to_int(e, &m));
  ck_assert_int_eq(0, from_decimal_to_int(f, &m));
  ck_assert_int_eq(m, -2147483648);
  ck_assert_int_eq(0, from_decimal_to_int(g, &m));
  ck_assert_int_eq(m, g.bits[0]);
  ck_assert_int_eq(0, from_decimal_to_int(h, &m));
  ck_assert_int_eq(m, 11);
  ck_assert_int_eq(0, from_decimal_to_int(i, &m));
  ck_assert_int_eq(m, -11);
}
END_TEST

START_TEST(dec_floor) {
  decimal a = {{33454, 0, 0, 262144}};      // 3345*e-4
  decimal b = {{33454, 0, 0, 2147745792}};  // -12345*e-4
  decimal e = {{4294967294, 4294967295, 4294967295, 0}};
  decimal d = {{10, 0, 0, 1900544}};  // степень 29
  decimal f = {{156666666, 0, 0, 458752}};
  decimal g = {{199999999, 0, 0, 458752}};
  decimal h = {{199999999, 0, 0, 2147942400}};
  decimal i = {{199999999, 0, 0, 0}};

  decimal res = {{0, 2, 2, 2}};

  ck_assert_int_eq(0, s_floor(a, &res));
  ck_assert_int_eq(res.bits[0], 3);
  ck_assert_int_eq(res.bits[1], 0);
  ck_assert_int_eq(res.bits[2], 0);
  ck_assert_int_eq(res.bits[3], 0);

  ck_assert_int_eq(0, s_floor(b, &res));
  ck_assert_int_eq(res.bits[0], 4);
  ck_assert_int_eq(res.bits[1], 0);
  ck_assert_int_eq(res.bits[2], 0);
  ck_assert_int_eq(res.bits[3], 2147483648);

  ck_assert_int_eq(0, s_floor(e, &res));
  ck_assert_int_eq(res.bits[0], e.bits[0]);
  ck_assert_int_eq(res.bits[1], e.bits[1]);
  ck_assert_int_eq(res.bits[2], e.bits[2]);
  ck_assert_int_eq(res.bits[3], e.bits[3]);

  ck_assert_int_eq(1, s_floor(d, &res));

  ck_assert_int_eq(0, s_floor(f, &res));
  ck_assert_int_eq(res.bits[0], 15);
  ck_assert_int_eq(res.bits[1], f.bits[1]);
  ck_assert_int_eq(res.bits[2], f.bits[2]);
  ck_assert_int_eq(res.bits[3], 0);

  ck_assert_int_eq(0, s_floor(g, &res));
  ck_assert_int_eq(res.bits[0], 19);
  ck_assert_int_eq(res.bits[1], g.bits[1]);
  ck_assert_int_eq(res.bits[2], g.bits[2]);
  ck_assert_int_eq(res.bits[3], 0);

  ck_assert_int_eq(0, s_floor(h, &res));
  ck_assert_int_eq(res.bits[0], 20);
  ck_assert_int_eq(res.bits[1], h.bits[1]);
  ck_assert_int_eq(res.bits[2], h.bits[2]);
  ck_assert_int_eq(res.bits[3], 2147483648);

  ck_assert_int_eq(0, s_floor(i, &res));
  ck_assert_int_eq(res.bits[0], i.bits[0]);
  ck_assert_int_eq(res.bits[1], i.bits[1]);
  ck_assert_int_eq(res.bits[2], i.bits[2]);
  ck_assert_int_eq(res.bits[3], i.bits[3]);
}
END_TEST

START_TEST(dec_round) {
  decimal a = {{2225, 0, 0, 2147549184}};
  decimal b = {{2235, 0, 0, 2147549184}};
  decimal c = {{35, 0, 0, 65536}};
  decimal d = {{25, 0, 0, 65536}};
  decimal e = {{4294967294, 4294967295, 4294967295, 0}};

  decimal res = {{0, 0, 0, 0}};
  decimal g = {{5, 5, 0, 196608}};

  ck_assert_int_eq(0, s_round(a, &res));
  ck_assert_int_eq(res.bits[0], 223);
  ck_assert_int_eq(res.bits[1], a.bits[1]);
  ck_assert_int_eq(res.bits[2], a.bits[2]);
  ck_assert_int_eq(res.bits[3], 2147483648);

  ck_assert_int_eq(0, s_round(b, &res));
  ck_assert_int_eq(res.bits[0], 224);
  ck_assert_int_eq(res.bits[1], b.bits[1]);
  ck_assert_int_eq(res.bits[2], b.bits[2]);
  ck_assert_int_eq(res.bits[3], 2147483648);

  ck_assert_int_eq(0, s_round(c, &res));
  ck_assert_int_eq(res.bits[0], 4);
  ck_assert_int_eq(res.bits[1], c.bits[1]);
  ck_assert_int_eq(res.bits[2], c.bits[2]);
  ck_assert_int_eq(res.bits[3], 0);

  ck_assert_int_eq(0, s_round(d, &res));
  ck_assert_int_eq(res.bits[0], 3);
  ck_assert_int_eq(res.bits[1], d.bits[1]);
  ck_assert_int_eq(res.bits[2], d.bits[2]);
  ck_assert_int_eq(res.bits[3], 0);

  ck_assert_int_eq(0, s_round(e, &res));
  ck_assert_int_eq(res.bits[0], e.bits[0]);
  ck_assert_int_eq(res.bits[1], e.bits[1]);
  ck_assert_int_eq(res.bits[2], e.bits[2]);
  ck_assert_int_eq(res.bits[3], e.bits[3]);

  ck_assert_int_eq(0, s_round(g, &res));
  ck_assert_int_eq(res.bits[0], 21474836);
  ck_assert_int_eq(res.bits[1], 0);
  ck_assert_int_eq(res.bits[2], 0);
  ck_assert_int_eq(res.bits[3], 0);
}
END_TEST

START_TEST(dec_truncate) {
  decimal a = {{2222, 0, 0, 196608}};

  decimal res = {{0, 0, 0, 0}};

  ck_assert_int_eq(0, truncate(a, &res));
  ck_assert_int_eq(res.bits[0], 2);
  ck_assert_int_eq(res.bits[1], a.bits[1]);
  ck_assert_int_eq(res.bits[2], a.bits[2]);
  ck_assert_int_eq(res.bits[3], 0);
}
END_TEST

START_TEST(dec_negate) {
  decimal a = {{0, 0, 0, 0}};
  decimal b = {{1, 0, 0, 2147483648}};
  decimal c = {{1, 0, 0, 2147483649}};
  decimal d = {{4294967294, 4294967295, 4294967295, 1835008}};
  decimal res = {{0, 0, 0, 0}};

  ck_assert_int_eq(0, negate(a, &res));
  ck_assert_int_eq(res.bits[0], a.bits[0]);
  ck_assert_int_eq(res.bits[1], a.bits[1]);
  ck_assert_int_eq(res.bits[2], a.bits[2]);
  ck_assert_int_eq(res.bits[3], 2147483648);

  ck_assert_int_eq(0, negate(b, &res));
  ck_assert_int_eq(res.bits[0], b.bits[0]);
  ck_assert_int_eq(res.bits[1], b.bits[1]);
  ck_assert_int_eq(res.bits[2], b.bits[2]);
  ck_assert_int_eq(res.bits[3], 0);

  ck_assert_int_eq(1, negate(c, &res));

  ck_assert_int_eq(0, negate(d, &res));
  ck_assert_int_eq(res.bits[0], d.bits[0]);
  ck_assert_int_eq(res.bits[1], d.bits[1]);
  ck_assert_int_eq(res.bits[2], d.bits[2]);
  ck_assert_int_eq(res.bits[3], 2149318656);
}
END_TEST

START_TEST(add1) {
  // 2 + 5
  decimal a = {{2, 0, 0, 0}};
  decimal b = {{5, 0, 0, 0}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{7, 0, 0, 0}};
  int resi = add(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(add2) {
  // 123456789 + 987654321
  decimal a = {{123456789, 0, 0, 0}};
  decimal b = {{987654321, 0, 0, 0}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{1111111110, 0, 0, 0}};
  int resi = add(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(add3) {
  // 2 + (-5)
  decimal a = {{2, 0, 0, 0}};
  decimal b = {{5, 0, 0, 2147483648}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{3, 0, 0, 2147483648}};
  int resi = add(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(add4) {
  // -2 + 5
  decimal a = {{2, 0, 0, 2147483648}};
  decimal b = {{5, 0, 0, 0}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{3, 0, 0, 0}};
  int resi = add(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(addPerepol) {
  // 79228162514264337593543950335 + 1
  decimal a = {{4294967295, 4294967295, 4294967295, 0}};
  decimal b = {{1, 0, 0, 0}};
  decimal res = {{0, 0, 0, 0}};
  int resi = add(a, b, &res);

  ck_assert_int_eq(resi, 1);
}
END_TEST

START_TEST(addPerepolOtr) {
  // -79228162514264337593543950335 - 1
  decimal a = {{4294967295, 4294967295, 4294967295, 2147483648}};
  decimal b = {{1, 0, 0, 2147483648}};
  decimal res = {{0, 0, 0, 0}};
  int resi = add(a, b, &res);

  ck_assert_int_eq(resi, 2);

  ///////////////////////////////////////////
}
END_TEST

START_TEST(sub1) {
  // -2 - (- 2)
  decimal a = {{2, 0, 0, 2147483648}};
  decimal b = {{2, 0, 0, 2147483648}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{0, 0, 0, 2147483648}};
  int resi = sub(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(sub2) {
  // 5 - 2
  decimal a = {{5, 0, 0, 0}};
  decimal b = {{2, 0, 0, 0}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{3, 0, 0, 0}};
  int resi = sub(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(subPerepol) {
  // 79228162514264337593543950335 - (-0.5)
  decimal a = {{4294967295, 4294967295, 4294967295, 0}};
  decimal b = {{5, 0, 0, 2147549184}};
  decimal res = {{0, 0, 0, 0}};
  int resi = sub(a, b, &res);

  ck_assert_int_eq(resi, 1);
}
END_TEST

START_TEST(subPerepolOtr) {
  // -79228162514264337593543950335 - 1
  decimal a = {{4294967295, 4294967295, 4294967295, 2147483648}};
  decimal b = {{1, 0, 0, 0}};
  decimal res = {{0, 0, 0, 0}};
  int resi = sub(a, b, &res);

  ck_assert_int_eq(resi, 2);
}
END_TEST

START_TEST(subBankCircle1) {
  // 79228162514264337593543950335 - 0.5
  decimal a = {{4294967295, 4294967295, 4294967295, 0}};
  decimal b = {{5, 0, 0, 65536}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{4294967294, 4294967295, 4294967295, 0}};
  int resi = sub(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);

  ///////////////////////////////////////////
  // drobno
}
END_TEST

START_TEST(drAdd1) {
  // 2.36 + 5.382141
  decimal a = {{236, 0, 0, 131072}};
  decimal b = {{5382141, 0, 0, 393216}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{7742141, 0, 0, 393216}};
  int resi = add(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(drAdd2) {
  // 123456789.36 + 987654321.281438 = 1111111110641438
  // 10 11011111110111000001110001011000 + 111000001001000100
  // 00110000111110110001100110011110 111111001010001100
  // 10110111000011100100011100011110
  decimal a = {{3755744344, 2, 0, 131072}};
  decimal b = {{821762462, 229956, 0, 393216}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{3071166238, 258700, 0, 393216}};
  int resi = add(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(drAdd3) {
  // 2.36 + (-5.382141)
  decimal a = {{236, 0, 0, 131072}};
  decimal b = {{5382141, 0, 0, 2147876864}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{3022141, 0, 0, 2147876864}};
  int resi = add(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(drAdd4) {
  // (-2.36) + 5.382141
  decimal a = {{236, 0, 0, 2147614720}};
  decimal b = {{5382141, 0, 0, 393216}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{3022141, 0, 0, 393216}};
  int resi = add(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(drSub1) {
  // (-2.36) - (-5.382141)
  decimal a = {{236, 0, 0, 2147614720}};
  decimal b = {{5382141, 0, 0, 2147876864}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{3022141, 0, 0, 393216}};
  int resi = sub(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(drSub2) {
  // 2.36 - 5.382141
  decimal a = {{236, 0, 0, 131072}};
  decimal b = {{5382141, 0, 0, 393216}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{3022141, 0, 0, 2147876864}};
  int resi = sub(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);

  // ///////////////////////////////////////////
  // // mul
}
END_TEST

START_TEST(mul1) {
  // 5 * 2
  decimal a = {{5, 0, 0, 0}};
  decimal b = {{2, 0, 0, 0}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{10, 0, 0, 0}};
  int resi = mul(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(mul2) {
  // 5 * (-2)
  decimal a = {{5, 0, 0, 0}};
  decimal b = {{2, 0, 0, 2147483648}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{10, 0, 0, 2147483648}};
  int resi = mul(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(mul3) {
  // (-5) * (-2)
  decimal a = {{5, 0, 0, 2147483648}};
  decimal b = {{2, 0, 0, 2147483648}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{10, 0, 0, 0}};
  int resi = mul(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(mul4) {
  // 2.36 * 5.382141
  decimal a = {{236, 0, 0, 131072}};
  decimal b = {{5382141, 0, 0, 393216}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{1270185276, 0, 0, 524288}};
  int resi = mul(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(mul5) {
  // 0 * 5.382141
  decimal a = {{0, 0, 0, 0}};
  decimal b = {{5382141, 0, 0, 393216}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{0, 0, 0, 0}};
  int resi = mul(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(mul6) {
  // 5.382141 * 0
  decimal a = {{5382141, 0, 0, 393216}};
  decimal b = {{0, 0, 0, 0}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{0, 0, 0, 0}};
  int resi = mul(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(mulPerepol) {
  // 79228162514264337593543950335 * 5
  decimal a = {{4294967295, 4294967295, 4294967295, 0}};
  decimal b = {{5, 0, 0, 0}};
  decimal res = {{0, 0, 0, 0}};
  int resi = mul(a, b, &res);

  ck_assert_int_eq(resi, 1);
}
END_TEST

START_TEST(mulPerepolOtr) {
  // -79228162514264337593543950335 * 5
  decimal a = {{4294967295, 4294967295, 4294967295, 2147483648}};
  decimal b = {{5, 0, 0, 0}};
  decimal res = {{0, 0, 0, 0}};
  int resi = mul(a, b, &res);

  ck_assert_int_eq(resi, 2);

  // ///////////////////////////////////////////
}
END_TEST

START_TEST(div1) {
  // 5 / 2
  decimal a = {{5, 0, 0, 0}};
  decimal b = {{2, 0, 0, 0}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{25, 0, 0, 65536}};
  int resi = s_div(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(div2) {
  // 6 / -2
  decimal a = {{6, 0, 0, 0}};
  decimal b = {{2, 0, 0, 2147483648}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{3, 0, 0, 2147483648}};
  int resi = s_div(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(div3) {
  // -6 / -2
  decimal a = {{6, 0, 0, 2147483648}};
  decimal b = {{2, 0, 0, 2147483648}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{3, 0, 0, 0}};
  int resi = s_div(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(div4) {
  // 6.25 / 2.5
  decimal a = {{625, 0, 0, 131072}};
  decimal b = {{25, 0, 0, 65536}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{250, 0, 0, 131072}};
  int resi = s_div(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(div5) {
  // 0 / 5.382141
  decimal a = {{0, 0, 0, 0}};
  decimal b = {{5382141, 0, 0, 393216}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{0, 0, 0, 0}};
  int resi = s_div(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(divPerepol) {
  // 79228162514264337593543950335 / 0.02
  decimal a = {{4294967295, 4294967295, 4294967295, 0}};
  decimal b = {{2, 0, 0, 131072}};
  decimal res = {{0, 0, 0, 0}};
  int resi = s_div(a, b, &res);

  ck_assert_int_eq(resi, 1);
}
END_TEST

START_TEST(divPerepolOtr) {
  // 79228162514264337593543950335 / -0.02
  decimal a = {{4294967295, 4294967295, 4294967295, 0}};
  decimal b = {{5, 0, 0, 2147614720}};
  decimal res = {{0, 0, 0, 0}};
  int resi = s_div(a, b, &res);

  ck_assert_int_eq(resi, 2);
}
END_TEST

START_TEST(divZero) {
  // 7 / 0
  decimal a = {{7, 0, 0, 0}};
  decimal b = {{0, 0, 0, 0}};
  decimal res = {{0, 0, 0, 0}};
  int resi = s_div(a, b, &res);

  ck_assert_int_eq(resi, 3);

  // ///////////////////////////////////////////
}
END_TEST

START_TEST(mod1) {
  // 5 % 2
  decimal a = {{5, 0, 0, 0}};
  decimal b = {{2, 0, 0, 0}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{1, 0, 0, 0}};
  int resi = mod(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(mod2) {
  // -6 % 2
  decimal a = {{6, 0, 0, 2147483648}};
  decimal b = {{2, 0, 0, 0}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{0, 0, 0, 0}};
  int resi = mod(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(mod3) {
  // -90 % -20
  decimal a = {{90, 0, 0, 2147483648}};
  decimal b = {{20, 0, 0, 2147483648}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{10, 0, 0, 2147483648}};
  int resi = mod(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(mod4) {
  // 6.25 % 2.5
  decimal a = {{625, 0, 0, 131072}};
  decimal b = {{25, 0, 0, 65536}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{125, 0, 0, 131072}};
  int resi = mod(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(mod5) {
  // 0.2 % 20
  decimal a = {{2, 0, 0, 65536}};
  decimal b = {{20, 0, 0, 0}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{2, 0, 0, 65536}};
  int resi = mod(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(mod6) {
  // 100 % 0.2
  decimal a = {{100, 0, 0, 0}};
  decimal b = {{2, 0, 0, 65536}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{0, 0, 0, 0}};
  int resi = mod(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(mod7) {
  // 1300000 % 0.4
  decimal a = {{1150981121, 30, 0, 0}};
  decimal b = {{4, 0, 0, 65536}};
  decimal res = {{0, 0, 0, 0}};
  decimal exp = {{2, 0, 0, 65536}};
  int resi = mod(a, b, &res);

  ck_assert_int_eq(resi, 0);
  ck_assert_int_eq(res.bits[0], exp.bits[0]);
  ck_assert_int_eq(res.bits[1], exp.bits[1]);
  ck_assert_int_eq(res.bits[2], exp.bits[2]);
  ck_assert_int_eq(res.bits[3], exp.bits[3]);
}
END_TEST

START_TEST(modZero) {
  // 7 / 0
  decimal a = {{7, 0, 0, 0}};
  decimal b = {{0, 0, 0, 0}};
  decimal res = {{0, 0, 0, 0}};
  int resi = mod(a, b, &res);

  ck_assert_int_eq(resi, 3);

  /////////////////////////////////////////////////////
}
END_TEST

START_TEST(round_1) {
  decimal src, origin, result;
  // src = 5.0;
  src.bits[0] = 0b00000000000000000000000000110010;
  src.bits[1] = 0b00000000000000000000000000000000;
  src.bits[2] = 0b00000000000000000000000000000000;
  src.bits[3] = 0b00000000000000010000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = 5;
  origin.bits[0] = 0b00000000000000000000000000000101;
  origin.bits[1] = 0b00000000000000000000000000000000;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b00000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_2) {
  decimal src, origin, result;
  // src = 3.4;
  src.bits[0] = 0b00000000000000000000000000100010;
  src.bits[1] = 0b00000000000000000000000000000000;
  src.bits[2] = 0b00000000000000000000000000000000;
  src.bits[3] = 0b00000000000000010000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = 3;
  origin.bits[0] = 0b00000000000000000000000000000011;
  origin.bits[1] = 0b00000000000000000000000000000000;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b00000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_3) {
  decimal src, origin, result;
  // src = 0.0;
  src.bits[0] = 0b00000000000000000000000000000000;
  src.bits[1] = 0b00000000000000000000000000000000;
  src.bits[2] = 0b00000000000000000000000000000000;
  src.bits[3] = 0b00000000000000010000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = 0;
  origin.bits[0] = 0b00000000000000000000000000000000;
  origin.bits[1] = 0b00000000000000000000000000000000;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b00000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_4) {
  decimal src, origin, result;
  // src = -2.4363463;
  src.bits[0] = 0b00000001011100111100000111000111;
  src.bits[1] = 0b00000000000000000000000000000000;
  src.bits[2] = 0b00000000000000000000000000000000;
  src.bits[3] = 0b10000000000001110000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = -2;
  origin.bits[0] = 0b00000000000000000000000000000010;
  origin.bits[1] = 0b00000000000000000000000000000000;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b10000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_5) {
  decimal src, origin, result;
  // src = -0.0;
  src.bits[0] = 0b00000000000000000000000000000000;
  src.bits[1] = 0b00000000000000000000000000000000;
  src.bits[2] = 0b00000000000000000000000000000000;
  src.bits[3] = 0b10000000000000010000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = 0;
  origin.bits[0] = 0b00000000000000000000000000000000;
  origin.bits[1] = 0b00000000000000000000000000000000;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b10000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_6) {
  decimal src, origin, result;
  // src = -0.45;
  src.bits[0] = 0b00000000000000000000000000101101;
  src.bits[1] = 0b00000000000000000000000000000000;
  src.bits[2] = 0b00000000000000000000000000000000;
  src.bits[3] = 0b10000000000000100000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = 0;
  origin.bits[0] = 0b00000000000000000000000000000000;
  origin.bits[1] = 0b00000000000000000000000000000000;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b10000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_7) {
  decimal src, origin, result;
  // src = 652.34631;
  src.bits[0] = 0b00000011111000110110011011000111;
  src.bits[1] = 0b00000000000000000000000000000000;
  src.bits[2] = 0b00000000000000000000000000000000;
  src.bits[3] = 0b00000000000001010000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = 652;
  origin.bits[0] = 0b00000000000000000000001010001100;
  origin.bits[1] = 0b00000000000000000000000000000000;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b00000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_8) {
  decimal src, origin, result;
  // src = 4.97623323;
  src.bits[0] = 0b00011101101010010010000100011011;
  src.bits[1] = 0b00000000000000000000000000000000;
  src.bits[2] = 0b00000000000000000000000000000000;
  src.bits[3] = 0b00000000000010000000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = 5;
  origin.bits[0] = 0b00000000000000000000000000000101;
  origin.bits[1] = 0b00000000000000000000000000000000;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b00000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_9) {
  decimal src, origin, result;
  // src = 65658654.59;
  src.bits[0] = 0b10000111010110110010011111110011;
  src.bits[1] = 0b00000000000000000000000000000001;
  src.bits[2] = 0b00000000000000000000000000000000;
  src.bits[3] = 0b00000000000000100000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = 65658655;
  origin.bits[0] = 0b00000011111010011101111100011111;
  origin.bits[1] = 0b00000000000000000000000000000000;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b00000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_10) {
  decimal src, origin, result;
  // src = -364748.110;
  src.bits[0] = 0b00010101101111011001110101001110;
  src.bits[1] = 0b00000000000000000000000000000000;
  src.bits[2] = 0b00000000000000000000000000000000;
  src.bits[3] = 0b10000000000000110000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = -364748;
  origin.bits[0] = 0b00000000000001011001000011001100;
  origin.bits[1] = 0b00000000000000000000000000000000;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b10000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_11) {
  decimal src, origin, result;
  // src = 1.9874565432111;
  src.bits[0] = 0b01101000011010011010001100101111;
  src.bits[1] = 0b00000000000000000001001000010011;
  src.bits[2] = 0b00000000000000000000000000000000;
  src.bits[3] = 0b00000000000011010000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = 2;
  origin.bits[0] = 0b00000000000000000000000000000010;
  origin.bits[1] = 0b00000000000000000000000000000000;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b00000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_12) {
  decimal src, origin, result;
  // src = -98.78798789312;
  src.bits[0] = 0b00010110010010101110101011000000;
  src.bits[1] = 0b00000000000000000000100011111100;
  src.bits[2] = 0b00000000000000000000000000000000;
  src.bits[3] = 0b10000000000010110000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = -99;
  origin.bits[0] = 0b00000000000000000000000001100011;
  origin.bits[1] = 0b00000000000000000000000000000000;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b10000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_13) {
  decimal src, origin, result;
  // src = 999999999999999999911.3;
  src.bits[0] = 0b10110010001111111111110010001001;
  src.bits[1] = 0b00011001111000001100100110111010;
  src.bits[2] = 0b00000000000000000000001000011110;
  src.bits[3] = 0b00000000000000010000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = 999999999999999999911;
  origin.bits[0] = 0b11011110100111111111111110100111;
  origin.bits[1] = 0b00110101110010011010110111000101;
  origin.bits[2] = 0b00000000000000000000000000110110;
  origin.bits[3] = 0b00000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_14) {
  decimal src, origin, result;
  // src = -545454512454545.35265454545645;
  src.bits[0] = 0b10000010111000100101101011101101;
  src.bits[1] = 0b11111001111010000010010110101101;
  src.bits[2] = 0b10110000001111101111000010010100;
  src.bits[3] = 0b10000000000011100000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = -545454512454545;
  origin.bits[0] = 0b10000110011101001011101110010001;
  origin.bits[1] = 0b00000000000000011111000000010110;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b10000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_15) {
  decimal src, origin, result;
  // src = 545454512454545.35265454545645;
  src.bits[0] = 0b10000010111000100101101011101101;
  src.bits[1] = 0b11111001111010000010010110101101;
  src.bits[2] = 0b10110000001111101111000010010100;
  src.bits[3] = 0b00000000000011100000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = 545454512454545;
  origin.bits[0] = 0b10000110011101001011101110010001;
  origin.bits[1] = 0b00000000000000011111000000010110;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b00000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_16) {
  decimal src, origin, result;
  // src = 7961327845421.879754123131254;
  src.bits[0] = 0b01001110111001000011100101110110;
  src.bits[1] = 0b01001011001101011010000111011001;
  src.bits[2] = 0b00011001101110010111010010111111;
  src.bits[3] = 0b00000000000011110000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = 7961327845422;
  origin.bits[0] = 0b10100100000111100100000000101110;
  origin.bits[1] = 0b00000000000000000000011100111101;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b00000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_17) {
  decimal src, origin, result;
  // src = 12345677.987654345678987654346;
  src.bits[0] = 0b10010001000010101111010011001010;
  src.bits[1] = 0b11000000010001011101010111110010;
  src.bits[2] = 0b00100111111001000001101100000000;
  src.bits[3] = 0b00000000000101010000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = 12345678;
  origin.bits[0] = 0b00000000101111000110000101001110;
  origin.bits[1] = 0b00000000000000000000000000000000;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b00000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_18) {
  decimal src, origin, result;
  // src = -12345677.987654345678987654346;
  src.bits[0] = 0b10010001000010101111010011001010;
  src.bits[1] = 0b11000000010001011101010111110010;
  src.bits[2] = 0b00100111111001000001101100000000;
  src.bits[3] = 0b10000000000101010000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = -12345678;
  origin.bits[0] = 0b00000000101111000110000101001110;
  origin.bits[1] = 0b00000000000000000000000000000000;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b10000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_19) {
  decimal src, origin, result;
  // src = 87654323456.9876545678987653;
  src.bits[0] = 0b00010001110011011101000110000101;
  src.bits[1] = 0b11110101101111000110111111000000;
  src.bits[2] = 0b00000010110101010000111100111111;
  src.bits[3] = 0b00000000000100000000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = 87654323457;
  origin.bits[0] = 0b01101000100110101101010100000001;
  origin.bits[1] = 0b00000000000000000000000000010100;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b00000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_20) {
  decimal src, origin, result;
  // src = 336565445454313.859865545;
  src.bits[0] = 0b00111110111111000101101111001001;
  src.bits[1] = 0b00111111110101011110000010001011;
  src.bits[2] = 0b00000000000000000100011101000101;
  src.bits[3] = 0b00000000000010010000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = 336565445454314;
  origin.bits[0] = 0b10111111110100011110100111101010;
  origin.bits[1] = 0b00000000000000010011001000011010;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b00000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_21) {
  decimal src, origin, result;
  // src = -15456451234534;
  src.bits[0] = 0b10111100010010010000101011100110;
  src.bits[1] = 0b00000000000000000000111000001110;
  src.bits[2] = 0b00000000000000000000000000000000;
  src.bits[3] = 0b10000000000000000000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = -15456451234534;
  origin.bits[0] = 0b10111100010010010000101011100110;
  origin.bits[1] = 0b00000000000000000000111000001110;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b10000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_22) {
  decimal src, origin, result;
  // src = -0.42354543545;
  src.bits[0] = 0b11011100100001110000101110111001;
  src.bits[1] = 0b00000000000000000000000000001001;
  src.bits[2] = 0b00000000000000000000000000000000;
  src.bits[3] = 0b10000000000010110000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = 0;
  origin.bits[0] = 0b00000000000000000000000000000000;
  origin.bits[1] = 0b00000000000000000000000000000000;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b10000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_23) {
  decimal src, origin, result;
  // src = 79228162514264337593543950335;
  src.bits[0] = 0b11111111111111111111111111111111;
  src.bits[1] = 0b11111111111111111111111111111111;
  src.bits[2] = 0b11111111111111111111111111111111;
  src.bits[3] = 0b00000000000000000000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = 79228162514264337593543950335;
  origin.bits[0] = 0b11111111111111111111111111111111;
  origin.bits[1] = 0b11111111111111111111111111111111;
  origin.bits[2] = 0b11111111111111111111111111111111;
  origin.bits[3] = 0b00000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_24) {
  decimal src, origin, result;
  // src = 2.7986531268974139743;
  src.bits[0] = 0b11111110100100001101100101011111;
  src.bits[1] = 0b10000100011001000010000111101000;
  src.bits[2] = 0b00000000000000000000000000000001;
  src.bits[3] = 0b00000000000100110000000000000000;
  int check = s_round(src, &result);
  int check_origin = 0;
  // origin = 3;
  origin.bits[0] = 0b00000000000000000000000000000011;
  origin.bits[1] = 0b00000000000000000000000000000000;
  origin.bits[2] = 0b00000000000000000000000000000000;
  origin.bits[3] = 0b00000000000000000000000000000000;
  ck_assert_int_eq(origin.bits[3], result.bits[3]);
  ck_assert_int_eq(origin.bits[2], result.bits[2]);
  ck_assert_int_eq(origin.bits[1], result.bits[1]);
  ck_assert_int_eq(origin.bits[0], result.bits[0]);
  ck_assert_int_eq(check, check_origin);
}
END_TEST

START_TEST(round_25) {
  decimal val = {{7, 7, 7, 0}};
  decimal res;
  s_round(val, &res);
  float fres = 0;
  from_decimal_to_float(res, &fres);
  float need = 129127208515966861312.0;
  ck_assert_float_eq(need, fres);
}
END_TEST

START_TEST(round_26) {
  decimal val = {{3, 3, 3, ~(UINT_MAX / 2)}};
  decimal res = {{0}};
  ck_assert_int_eq(0, s_round(val, &res));
}
END_TEST

START_TEST(round_27) {
  decimal val = {{3, 3, 3, 0}};
  decimal res = {{0}};
  changeScale(&val, 5);
  ck_assert_int_eq(0, s_round(val, &res));
}
END_TEST

START_TEST(round_28) {
  decimal val = {{7, 7, 7, ~(UINT_MAX / 2)}};
  decimal res = {{0}};
  changeScale(&val, 5);
  ck_assert_int_eq(0, s_round(val, &res));
}
END_TEST

START_TEST(round_29) {
  decimal val = {{25, 0, 0, ~(UINT_MAX / 2)}};
  decimal res = {{0}};
  changeScale(&val, 1);
  ck_assert_int_eq(0, s_round(val, &res));
}
END_TEST

START_TEST(round_30) {
  decimal val = {{26, 0, 0, 0}};
  decimal res = {{0}};
  changeScale(&val, 1);
  ck_assert_int_eq(0, s_round(val, &res));
}
END_TEST

START_TEST(round_31) {
  decimal val = {{115, 0, 0, 0}};
  decimal res = {{0}};
  changeScale(&val, 1);
  ck_assert_int_eq(0, s_round(val, &res));
}
END_TEST

START_TEST(round_32) {
  decimal val = {{118, 0, 0, 0}};
  decimal res = {{0}};
  changeScale(&val, 1);
  ck_assert_int_eq(0, s_round(val, &res));
}
END_TEST

START_TEST(round_33) {
  decimal val = {{125, 0, 0, 0}};
  decimal res = {{0}};
  changeScale(&val, 1);
  ck_assert_int_eq(0, s_round(val, &res));
}
END_TEST

START_TEST(round_34) {
  decimal val = {{128, 0, 0, 0}};
  decimal res = {{0}};
  changeScale(&val, 1);
  s_round(val, &res);
  float fres = 0;
  from_decimal_to_float(res, &fres);
  float need = 13;
  ck_assert_float_eq(need, fres);
}
END_TEST

START_TEST(round_35) {
  decimal value_1 = {{7464923, 0, 0, 0}};
  changeScale(&value_1, 5);
  decimal check = {{75, 0, 0, 0}};
  decimal result = {0};
  int return_value = s_round(value_1, &result);
  ck_assert_int_eq(is_equal(result, check), 1);
  ck_assert_int_eq(return_value, 0);
}
END_TEST

START_TEST(round_36) {
  decimal value_1 = {{7444923, 0, 0, 0}};
  changeScale(&value_1, 5);
  decimal check = {{74, 0, 0, 0}};
  decimal result = {0};
  int return_value = s_round(value_1, &result);
  ck_assert_int_eq(is_equal(result, check), 1);
  ck_assert_int_eq(return_value, 0);
}
END_TEST

START_TEST(round_37) {
  decimal src1 = {0};
  src1.bits[0] = 0b01010101001110101110101110110001;
  src1.bits[1] = 0b00001101101101001101101001011111;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b10000000000100100000000000000000;
  decimal result = {0};
  result.bits[0] = 0b00000000000000000000000000000001;
  result.bits[1] = 0b00000000000000000000000000000000;
  result.bits[2] = 0b00000000000000000000000000000000;
  result.bits[3] = 0b10000000000000000000000000000000;
  decimal res_od = {0};
  s_round(src1, &res_od);
  ck_assert_float_eq(res_od.bits[0], result.bits[0]);
  ck_assert_float_eq(res_od.bits[1], result.bits[1]);
  ck_assert_float_eq(res_od.bits[2], result.bits[2]);
  ck_assert_float_eq(res_od.bits[3], result.bits[3]);
}
END_TEST

START_TEST(round_38) {
  decimal src1 = {0};
  src1.bits[0] = 0b10010111011100111001111111111111;
  src1.bits[1] = 0b00111100000010000011000110001101;
  src1.bits[2] = 0b00000000000000000000000000000001;
  src1.bits[3] = 0b10000000000001110000000000000000;
  decimal res_od = {0};
  s_round(src1, &res_od);
  decimal result = {0};
  result.bits[3] = 0b10000000000000000000000000000000;
  result.bits[2] = 0;
  result.bits[1] = 0b00000000000000000000001000010010;
  result.bits[0] = 0b00110110101101101000110001000000;
  ck_assert_float_eq(res_od.bits[0], result.bits[0]);
  ck_assert_float_eq(res_od.bits[1], result.bits[1]);
  ck_assert_float_eq(res_od.bits[2], result.bits[2]);
  ck_assert_float_eq(res_od.bits[3], result.bits[3]);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, test_is_less);
  tcase_add_test(tc1_1, test_is_equal);
  tcase_add_test(tc1_1, test_is_less_or_equal);
  tcase_add_test(tc1_1, test_is_greater);
  tcase_add_test(tc1_1, test_is_greater_or_equal);
  tcase_add_test(tc1_1, test_is_not_equal);
  tcase_add_test(tc1_1, test_from_float_to_decimal);
  tcase_add_test(tc1_1, test_from_decimal_to_float);
  tcase_add_test(tc1_1, test_from_int_to_decimal);
  tcase_add_test(tc1_1, test_from_decimal_to_int);
  tcase_add_test(tc1_1, dec_floor);
  tcase_add_test(tc1_1, dec_round);
  tcase_add_test(tc1_1, dec_truncate);
  tcase_add_test(tc1_1, dec_negate);
  tcase_add_test(tc1_1, add1);
  tcase_add_test(tc1_1, add2);
  tcase_add_test(tc1_1, add3);
  tcase_add_test(tc1_1, add4);
  tcase_add_test(tc1_1, addPerepol);
  tcase_add_test(tc1_1, addPerepolOtr);
  tcase_add_test(tc1_1, sub1);
  tcase_add_test(tc1_1, sub2);
  tcase_add_test(tc1_1, subPerepol);
  tcase_add_test(tc1_1, subPerepolOtr);
  tcase_add_test(tc1_1, subBankCircle1);
  tcase_add_test(tc1_1, drAdd1);
  tcase_add_test(tc1_1, drAdd2);
  tcase_add_test(tc1_1, drAdd3);
  tcase_add_test(tc1_1, drAdd4);
  tcase_add_test(tc1_1, drSub1);
  tcase_add_test(tc1_1, drSub2);
  tcase_add_test(tc1_1, mul1);
  tcase_add_test(tc1_1, mul2);
  tcase_add_test(tc1_1, mul3);
  tcase_add_test(tc1_1, mul4);
  tcase_add_test(tc1_1, mul5);
  tcase_add_test(tc1_1, mul6);
  tcase_add_test(tc1_1, mulPerepol);
  tcase_add_test(tc1_1, mulPerepolOtr);
  tcase_add_test(tc1_1, div1);
  tcase_add_test(tc1_1, div2);
  tcase_add_test(tc1_1, div3);
  tcase_add_test(tc1_1, div4);
  tcase_add_test(tc1_1, div5);
  tcase_add_test(tc1_1, divPerepol);
  tcase_add_test(tc1_1, divPerepolOtr);
  tcase_add_test(tc1_1, divZero);
  tcase_add_test(tc1_1, mod1);
  tcase_add_test(tc1_1, mod2);
  tcase_add_test(tc1_1, mod3);
  tcase_add_test(tc1_1, mod4);
  tcase_add_test(tc1_1, mod5);
  tcase_add_test(tc1_1, mod6);
  tcase_add_test(tc1_1, mod7);
  tcase_add_test(tc1_1, modZero);
  tcase_add_test(tc1_1, round_1);
  tcase_add_test(tc1_1, round_2);
  tcase_add_test(tc1_1, round_3);
  tcase_add_test(tc1_1, round_4);
  tcase_add_test(tc1_1, round_5);
  tcase_add_test(tc1_1, round_6);
  tcase_add_test(tc1_1, round_7);
  tcase_add_test(tc1_1, round_8);
  tcase_add_test(tc1_1, round_9);
  tcase_add_test(tc1_1, round_10);
  tcase_add_test(tc1_1, round_11);
  tcase_add_test(tc1_1, round_12);
  tcase_add_test(tc1_1, round_13);
  tcase_add_test(tc1_1, round_14);
  tcase_add_test(tc1_1, round_15);
  tcase_add_test(tc1_1, round_16);
  tcase_add_test(tc1_1, round_17);
  tcase_add_test(tc1_1, round_18);
  tcase_add_test(tc1_1, round_19);
  tcase_add_test(tc1_1, round_20);
  tcase_add_test(tc1_1, round_21);
  tcase_add_test(tc1_1, round_22);
  tcase_add_test(tc1_1, round_23);
  tcase_add_test(tc1_1, round_24);
  tcase_add_test(tc1_1, round_25);
  tcase_add_test(tc1_1, round_26);
  tcase_add_test(tc1_1, round_27);
  tcase_add_test(tc1_1, round_28);
  tcase_add_test(tc1_1, round_29);
  tcase_add_test(tc1_1, round_30);
  tcase_add_test(tc1_1, round_31);
  tcase_add_test(tc1_1, round_32);
  tcase_add_test(tc1_1, round_33);
  tcase_add_test(tc1_1, round_34);
  tcase_add_test(tc1_1, round_35);
  tcase_add_test(tc1_1, round_36);
  tcase_add_test(tc1_1, round_37);
  tcase_add_test(tc1_1, round_38);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
