/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source
 * file "test.check" instead.
 */

#include <check.h>
#include <math.h>
#include <stdlib.h>

#include "Smath.h"
#ifdef __linux__
#define finite(v) (__builtin_isfinite(v))
#define M_PI 3.14159265358979323846
#endif

double inf_max = 1.0 / 0.0;
double inf_min = -1.0 / 0.0;
double nan_max = 0.0 / 0.0;
double nan_min = -0.0 / 0.0;

START_TEST(test_sinLoop) {
  long double res = sin(_i);
  long double res_s = s_sin(_i);
  long double ex = fabs((double)(res - res_s));
  ck_assert_msg(ex <= S_EPSSR, "\n%d\nres: %Lf\nr21: %Lf\n", _i, res, res_s);
}
END_TEST

START_TEST(test_sinInf) {
  long double res_s = s_sin(S_INF_MAX);
  ck_assert(!finite(res_s));
}
END_TEST

START_TEST(test_sinNan) {
  long double res_s = s_sin(S_NAN);
  ck_assert(!finite(res_s));
  /////////////////////////////
}
END_TEST

START_TEST(test_cosLoop) {
  long double res = cos(_i);
  long double res_s = s_cos(_i);
  long double ex = fabs((double)(res - res_s));
  ck_assert_msg(ex <= S_EPSSR, "\n%d\nres: %Lf\nr21: %Lf\n", _i, res, res_s);
}
END_TEST

START_TEST(test_cosInf) {
  long double res_s = s_cos(S_INF_MAX);
  ck_assert(!finite(res_s));
}
END_TEST

START_TEST(test_cosNan) {
  long double res_s = s_cos(S_NAN);
  ck_assert(!finite(res_s));
  ///////////////////////////////
}
END_TEST

START_TEST(test_tanLoop) {
  long double res = tan(_i);
  long double res_s = s_tan(_i);
  long double ex = fabs((double)(res - res_s));
  ck_assert_msg(ex <= S_EPSSR, "\n%d\nres: %Lf\nr21: %Lf\n", _i, res, res_s);
}
END_TEST

START_TEST(test_tanInf) {
  long double res_s = s_tan(S_INF_MAX);
  ck_assert(!finite(res_s));
}
END_TEST

START_TEST(test_tanNan) {
  long double res_s = s_tan(S_NAN);
  ck_assert(!finite(res_s));
  // ///////////////////////////////
}
END_TEST

START_TEST(test_atanLoop) {
  long double res = atan(_i);
  long double res_s = s_atan(_i);
  long double ex = fabs((double)(res - res_s));
  ck_assert_msg(ex <= S_EPSSR, "\n%d\nres: %Lf\nr21: %Lf\n", _i, res, res_s);
}
END_TEST

START_TEST(test_atanInf) {
  long double res_s = s_atan(S_INF_MAX);
  // ck_assert(!finite(res_s));
  long double ex = fabs((double)(M_PI / 2 - res_s));
  ck_assert_msg(ex <= S_EPSSR, "r21: %Lf\n", res_s);
}
END_TEST

START_TEST(test_atanNan) {
  long double res_s = s_atan(S_NAN);
  ck_assert(!finite(res_s));
  ///////////////////////////////
}
END_TEST

START_TEST(test_asinLoopM10) {
  long double res = asin((double)_i / 100);
  long double res_s = s_asin((double)_i / 100);
  long double ex = fabs((double)(res - res_s));
  ck_assert_msg(ex <= S_EPSSR, "\n%f\nres: %Lf\nr21: %Lf\n", (double)_i / 100,
                res, res_s);
}
END_TEST

START_TEST(test_asinLoop01) {
  long double res = asin(_i / 100);
  long double res_s = s_asin(_i / 100);
  long double ex = fabs((double)(res - res_s));
  ck_assert_msg(ex <= S_EPSSR, "\n%f\nres: %Lf\nr21: %Lf\n", (double)_i / 100,
                res, res_s);
}
END_TEST

START_TEST(test_asinLoopM) {
  long double res_s = s_asin(_i);
  ck_assert(!finite(res_s));
}
END_TEST

START_TEST(test_asinLoopP) {
  long double res_s = s_asin(_i);
  ck_assert(!finite(res_s));
}
END_TEST

START_TEST(test_asinOne) {
  long double res_s = s_asin(1);
  long double ex = fabs((double)(M_PI / 2 - res_s));
  ck_assert(ex <= S_EPSSR);
}
END_TEST

START_TEST(test_asinMinusOne) {
  long double res_s = s_asin(-1);
  long double ex = fabs((double)(-M_PI / 2 - res_s));
  ck_assert(ex <= S_EPSSR);
}
END_TEST

START_TEST(test_asinInf) {
  long double res_s = s_asin(S_INF_MAX);
  ck_assert(!finite(res_s));
}
END_TEST

START_TEST(test_asinNan) {
  long double res_s = s_asin(S_NAN);
  ck_assert(!finite(res_s));
  ///////////////////////////////
}
END_TEST

START_TEST(test_acosLoopM10) {
  long double res = acos((double)_i / 100);
  long double res_s = s_acos((double)_i / 100);
  long double ex = fabs((double)(res - res_s));
  ck_assert_msg(ex <= S_EPSSR, "\n%f\nres: %Lf\nr21: %Lf\n", (double)_i / 100,
                res, res_s);
}
END_TEST

START_TEST(test_acosLoop01) {
  long double res = acos(_i / 100);
  long double res_s = s_acos(_i / 100);
  long double ex = fabs((double)(res - res_s));
  ck_assert_msg(ex <= S_EPSSR, "\n%f\nres: %Lf\nr21: %Lf\n", (double)_i / 100,
                res, res_s);
}
END_TEST

START_TEST(test_acosLoopM) {
  long double res_s = s_acos(_i);
  ck_assert(!finite(res_s));
}
END_TEST

START_TEST(test_acosLoopP) {
  long double res_s = s_acos(_i);
  ck_assert(!finite(res_s));
}
END_TEST

START_TEST(test_acosOne) {
  long double res_s = s_acos(1);
  long double ex = fabs((double)(0 - res_s));
  ck_assert(ex <= S_EPSSR);
}
END_TEST

START_TEST(test_acosInf) {
  long double res_s = s_acos(S_INF_MAX);
  ck_assert(!finite(res_s));
}
END_TEST

START_TEST(test_acosNan) {
  long double res_s = s_acos(S_NAN);
  ck_assert(!finite(res_s));
  /////////////////////////////
}
END_TEST

START_TEST(test_logLoop) {
  long double res = log(_i);
  long double res_s = s_log(_i);
  long double ex = fabs((double)(res - res_s));
  ck_assert_msg(ex <= S_EPSSR, "\n%d\nres: %Lf\nr21: %Lf\n", _i, res, res_s);
}
END_TEST

START_TEST(test_logMinus) {
  long double res_s = s_log(S_INF_MAX);
  ck_assert(!finite(res_s));
}
END_TEST

START_TEST(test_logInf) {
  long double res_s = s_log(S_INF_MAX);
  ck_assert(!finite(res_s));
}
END_TEST

START_TEST(test_logNan) {
  long double res_s = s_log(S_NAN);
  ck_assert(!finite(res_s));
  /////////////////////////////
}
END_TEST

START_TEST(test_expLoop) {
  long double res = exp(_i);
  long double res_s = s_exp(_i);
  while (res > 10000000000) res = res / 10;
  while (res_s > 10000000000) res_s = res_s / 10;
  long double ex = fabs((double)(res - res_s));
  ck_assert_msg(ex <= S_EPSSR, "\n%d\nres: %Lf\nr21: %Lf\n", _i, res, res_s);
}
END_TEST

START_TEST(test_expInf) {
  long double res_s = s_exp(S_INF_MAX);
  ck_assert(!finite(res_s));
}
END_TEST

START_TEST(test_expNan) {
  long double res_s = s_exp(S_NAN);
  ck_assert(!finite(res_s));
  ///////////////////////////////
}
END_TEST

START_TEST(test_abs) {
  // int inf_max = 1.0 / 0.0;
  // int inf_min = -1.0 / 0.0;
  // int nan_max = 0.0 / 0.0;
  // int nan_min = -0.0 / 0.0;

  ck_assert_int_eq(s_abs(inf_max), abs((int)inf_max));
  ck_assert_int_eq(s_abs(inf_min), abs((int)inf_min));
  ck_assert_int_eq(s_abs(nan_max), abs((int)nan_max));
  ck_assert_int_eq(s_abs(nan_min), abs((int)nan_min));

  ck_assert_int_eq(s_abs(-10), abs(-10));
  ck_assert_int_eq(s_abs(-0), abs(-0));
  ck_assert_int_eq(s_abs(+0), abs(+0));
  ck_assert_int_eq(s_abs(10), abs(10));
}
END_TEST

START_TEST(test_fabs) {
  // double inf_max = 1.0 / 0.0;
  // double inf_min = -1.0 / 0.0;
  // double nan_max = 0.0 / 0.0;
  // double nan_min = -0.0 / 0.0;

  ck_assert_int_eq(s_fabs(inf_max), fabs((double)inf_max));
  ck_assert_int_eq(s_fabs(inf_min), fabs((double)inf_min));
  ck_assert_int_eq(s_fabs(nan_max), fabs((double)nan_max));
  ck_assert_int_eq(s_fabs(nan_min), fabs((double)nan_min));
  ck_assert_ldouble_infinite(s_fabs(inf_max));
  ck_assert_ldouble_infinite(s_fabs(inf_min));
  ck_assert_ldouble_eq_tol(s_fabs(0.5), fabs(0.5), 1e-6);
  ck_assert_ldouble_nan(s_fabs(nan_max));
  ck_assert_ldouble_nan(s_fabs(nan_min));
  ck_assert_ldouble_eq_tol(s_fabs(-10.2), fabs(-10.2), 1e-6);
  ck_assert_ldouble_eq_tol(s_fabs(-10.999999), fabs(-10.999999), 1e-6);
  ck_assert_ldouble_eq_tol(s_fabs(-0.0), fabs(-0.0), 1e-6);
  ck_assert_ldouble_eq_tol(s_fabs(10.5), fabs(10.5), 1e-6);
  ck_assert_ldouble_eq_tol(s_fabs(1700000000000000.999999),
                           fabs(1700000000000000.999999), 1e-6);
  ck_assert_ldouble_eq_tol(s_fabs(-1700000000000000.999999),
                           fabs(-1700000000000000.999999), 1e-6);
}
END_TEST

START_TEST(test_floor) {
  // double inf_max = 1.0 / 0.0;
  // double inf_min = -1.0 / 0.0;
  // double nan_max = 0.0 / 0.0;
  // double nan_min = -0.0 / 0.0;

  ck_assert_int_eq(s_floor(inf_max), floor(inf_max));
  ck_assert_int_eq(s_floor(inf_min), floor(inf_min));
  ck_assert_int_eq(s_floor(nan_max), floor(nan_max));
  ck_assert_int_eq(s_floor(nan_min), floor(nan_min));
  ck_assert_ldouble_infinite(s_floor(inf_max));
  ck_assert_ldouble_infinite(s_floor(inf_min));
  ck_assert_ldouble_nan(s_floor(nan_max));
  ck_assert_ldouble_nan(s_floor(nan_min));
  ck_assert_ldouble_eq(s_floor(0.0), floor(0.0));
  ck_assert_ldouble_eq(s_floor(-0.0), floor(-0.0));
  ck_assert_ldouble_eq(s_floor(1700000000000000.999999),
                       floor(1700000000000000.999999));
  ck_assert_ldouble_eq(s_floor(-1700000000000000.999999),
                       floor(-1700000000000000.999999));
  ck_assert_ldouble_eq(s_floor(10.5), floor(10.5));
  ck_assert_ldouble_eq(s_floor(0.5), floor(0.5));
  ck_assert_ldouble_eq(s_floor(-0.45), floor(-0.45));
  ck_assert_ldouble_eq(s_floor(-0.000009), floor(-0.000009));
}
END_TEST

START_TEST(test_ceil) {
  // double inf_max = 1.0 / 0.0;
  // double inf_min = -1.0 / 0.0;
  // double nan_max = 0.0 / 0.0;
  // double nan_min = -0.0 / 0.0;

  ck_assert_int_eq(s_ceil(inf_max), ceil(inf_max));
  ck_assert_int_eq(s_ceil(inf_min), ceil(inf_min));
  ck_assert_int_eq(s_ceil(nan_max), ceil(nan_max));
  ck_assert_int_eq(s_ceil(nan_min), ceil(nan_min));
  ck_assert_ldouble_infinite(s_ceil(inf_max));
  ck_assert_ldouble_infinite(s_ceil(inf_min));
  ck_assert_ldouble_nan(s_ceil(nan_max));
  ck_assert_ldouble_nan(s_ceil(nan_min));
  ck_assert_ldouble_eq(s_ceil(0.0), ceil(0.0));
  ck_assert_ldouble_eq(s_ceil(-0.0), ceil(-0.0));
  ck_assert_ldouble_eq(s_ceil(1700000000000000.999999),
                       ceil(1700000000000000.999999));
  ck_assert_ldouble_eq(s_ceil(-1700000000000000.999999),
                       ceil(-1700000000000000.999999));
  ck_assert_ldouble_eq(s_ceil(10.5), ceil(10.5));
  ck_assert_ldouble_eq(s_ceil(0.5), ceil(0.5));
  ck_assert_ldouble_eq(s_ceil(-0.45), ceil(-0.45));
  ck_assert_ldouble_eq(s_ceil(-0.000009), ceil(-0.000009));
}
END_TEST

START_TEST(test_pow) {
  // double inf_max = 1.0 / 0.0;
  // double inf_min = -1.0 / 0.0;
  // double nan_max = 0.0 / 0.0;
  // double nan_min = -0.0 / 0.0;

  ck_assert_ldouble_eq_tol(s_pow(1, nan_max), pow(1, nan_max), 1e-6);
  ck_assert_ldouble_eq_tol(s_pow(nan_max, 0), pow(nan_max, 0), 1e-6);
  ck_assert_ldouble_eq_tol(s_pow(1, inf_max), pow(1, inf_max), 1e-6);
  ck_assert_ldouble_eq_tol(s_pow(inf_max, 0), pow(inf_max, 0), 1e-6);

  ck_assert_ldouble_eq(s_pow(inf_max, inf_max), pow(inf_max, inf_max));
  ck_assert_ldouble_eq(s_pow(inf_max, inf_min), pow(inf_max, inf_min));
  ck_assert_ldouble_nan(s_pow(inf_min, nan_max));
  ck_assert_ldouble_nan(s_pow(inf_min, nan_min));
  ck_assert_ldouble_nan(s_pow(nan_max, inf_min));
  ck_assert_ldouble_nan(s_pow(nan_min, inf_min));

  ck_assert_ldouble_infinite(s_pow(0.5, inf_min));
  ck_assert_ldouble_infinite(s_pow(1.5, inf_max));
  ck_assert_ldouble_eq_tol(s_pow(1.5, inf_min), pow(1.5, inf_min), 1e-6);
  ck_assert_ldouble_eq_tol(s_pow(0.5, inf_max), pow(0.5, inf_max), 1e-6);
  ck_assert_ldouble_eq(s_pow(0.5, inf_min), pow(0.5, inf_min));

  ck_assert_ldouble_eq_tol(s_pow(inf_min, -4), pow(inf_min, -4), 1e-6);
  ck_assert_ldouble_eq(s_pow(inf_min, 4.4), pow(inf_min, 4.4));
  ck_assert_ldouble_eq_tol(s_pow(inf_min, -4.4), pow(inf_min, -4.4), 1e-6);
  // ck_assert_ldouble_eq(s_pow(inf_min, 4), pow(inf_min, 4));

  ck_assert_ldouble_eq_tol(s_pow(inf_max, -5.5), pow(inf_max, -5.5), 1e-6);
  ck_assert_ldouble_eq(s_pow(inf_max, 4.4), pow(inf_max, 4.4));

  ck_assert_ldouble_eq_tol(s_pow(0, 5), pow(0, 5), 1e-6);
  ck_assert_ldouble_eq_tol(s_pow(-0, 5), pow(-0, 5), 1e-6);
  // ck_assert_ldouble_eq(s_pow(0, -5), pow(0, -5));
  // ck_assert_ldouble_eq(s_pow(-0, -5), pow(-0, -5));
  // ck_assert_ldouble_eq(s_pow(-0, -6), pow(-0, -6));
  ck_assert_ldouble_eq(s_pow(0, -6.6), pow(0, -6.6));
  ck_assert_ldouble_eq(s_pow(-0, -6.6), pow(-0, -6.6));
  ck_assert_ldouble_eq(s_pow(-0, 6.6), pow(-0, 6.6));
  ck_assert_ldouble_eq(s_pow(0, 6.6), pow(0, 6.6));

  ck_assert_ldouble_eq_tol(s_pow(-1, inf_max), pow(-1, inf_max), 1e-6);
  ck_assert_ldouble_eq_tol(s_pow(-1, inf_min), pow(-1, inf_min), 1e-6);

  ck_assert_ldouble_nan(s_pow(-1, 2.2));
  ck_assert_ldouble_eq_tol(s_pow(-2, 4), pow(-2, 4), 1e-6);
  ck_assert_ldouble_eq_tol(s_pow(-1, -12), pow(-1, -12), 1e-6);

  ck_assert_ldouble_eq_tol(s_pow(3.3, -24.2), pow(3.3, -24.2), 1e-6);
  ck_assert_ldouble_eq_tol(s_pow(-3.3, 3), pow(-3.3, 3), 1e-6);
  ck_assert_ldouble_nan(s_pow(-3.3, -24.2));
}
END_TEST

START_TEST(test_sqrt) {
  // double inf_max = 1.0 / 0.0;
  // double inf_min = -1.0 / 0.0;
  // double nan_max = 0.0 / 0.0;
  // double nan_min = -0.0 / 0.0;

  ck_assert_ldouble_nan(s_sqrt(inf_min));
  ck_assert_ldouble_infinite(s_sqrt(inf_max));
  ck_assert_ldouble_nan(s_sqrt(nan_max));
  ck_assert_ldouble_nan(s_sqrt(nan_min));
  ck_assert_ldouble_eq_tol(s_sqrt(0.5), sqrt(0.5), 1e-6);
  ck_assert_ldouble_nan(s_sqrt(-0.5));
  ck_assert_ldouble_eq_tol(s_sqrt(1), sqrt(1), 1e-6);
  ck_assert_ldouble_eq_tol(s_sqrt(1.1), sqrt(1.1), 1e-6);
  ck_assert_ldouble_eq_tol(s_sqrt(0), sqrt(0), 1e-6);
  ck_assert_ldouble_eq_tol(s_sqrt(-0), sqrt(-0), 1e-6);
  ck_assert_ldouble_eq_tol(s_sqrt(5.123456789123), sqrt(5.123456789123), 1e-6);
  ck_assert_ldouble_eq_tol(s_sqrt(0.00000004564897), sqrt(0.00000004564897),
                           1e-6);
  ck_assert_ldouble_eq_tol(s_sqrt(170000000000000.1), sqrt(170000000000000.1),
                           1e-6);
}
END_TEST

START_TEST(test_fmod) {
  // double inf_max = 1.0 / 0.0;
  // double inf_min = -1.0 / 0.0;
  // double nan_max = 0.0 / 0.0;
  // double nan_min = -0.0 / 0.0;

  ck_assert_ldouble_nan(s_fmod(inf_max, inf_max));
  ck_assert_ldouble_nan(s_fmod(inf_max, inf_min));
  ck_assert_ldouble_nan(s_fmod(inf_max, nan_max));
  ck_assert_ldouble_nan(s_fmod(inf_max, nan_min));

  ck_assert_ldouble_nan(s_fmod(inf_min, inf_max));
  ck_assert_ldouble_nan(s_fmod(inf_min, inf_min));
  ck_assert_ldouble_nan(s_fmod(inf_min, nan_max));
  ck_assert_ldouble_nan(s_fmod(inf_min, nan_min));

  ck_assert_ldouble_nan(s_fmod(nan_max, inf_max));
  ck_assert_ldouble_nan(s_fmod(nan_max, inf_min));
  ck_assert_ldouble_nan(s_fmod(nan_max, nan_max));
  ck_assert_ldouble_nan(s_fmod(nan_max, nan_min));
  ck_assert_ldouble_eq_tol(s_fmod(2.4, inf_max), fmod(2.4, inf_max), 1e-8);
  ck_assert_ldouble_eq_tol(s_fmod(2.4, inf_min), fmod(2.4, inf_min), 1e-8);

  ck_assert_ldouble_eq_tol(s_fmod(2.4, 0.5), fmod(2.4, 0.5), 1e-8);
  ck_assert_ldouble_eq_tol(s_fmod(2.4, -0.5), fmod(2.4, -0.5), 1e-8);
  ck_assert_ldouble_eq_tol(s_fmod(-2.4, 0.5), fmod(-2.4, 0.5), 1e-8);
  ck_assert_ldouble_eq_tol(s_fmod(-2.4, -0.5), fmod(-2.4, -0.5), 1e-8);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_loop_test(tc1_1, test_sinLoop, -200, 200);
  tcase_add_test(tc1_1, test_sinInf);
  tcase_add_test(tc1_1, test_sinNan);
  tcase_add_loop_test(tc1_1, test_cosLoop, -200, 200);
  tcase_add_test(tc1_1, test_cosInf);
  tcase_add_test(tc1_1, test_cosNan);
  tcase_add_loop_test(tc1_1, test_tanLoop, -200, 200);
  tcase_add_test(tc1_1, test_tanInf);
  tcase_add_test(tc1_1, test_tanNan);
  tcase_add_loop_test(tc1_1, test_atanLoop, -200, 200);
  tcase_add_test(tc1_1, test_atanInf);
  tcase_add_test(tc1_1, test_atanNan);
  tcase_add_loop_test(tc1_1, test_asinLoopM10, -10, 10);
  tcase_add_loop_test(tc1_1, test_asinLoop01, 1, 10);
  tcase_add_loop_test(tc1_1, test_asinLoopM, -10, -2);
  tcase_add_loop_test(tc1_1, test_asinLoopP, 2, 10);
  tcase_add_test(tc1_1, test_asinOne);
  tcase_add_test(tc1_1, test_asinMinusOne);
  tcase_add_test(tc1_1, test_asinInf);
  tcase_add_test(tc1_1, test_asinNan);
  tcase_add_loop_test(tc1_1, test_acosLoopM10, -10, 0);
  tcase_add_loop_test(tc1_1, test_acosLoop01, 0, 10);
  tcase_add_loop_test(tc1_1, test_acosLoopM, -10, -2);
  tcase_add_loop_test(tc1_1, test_acosLoopP, 2, 10);
  tcase_add_test(tc1_1, test_acosOne);
  tcase_add_test(tc1_1, test_acosInf);
  tcase_add_test(tc1_1, test_acosNan);
  tcase_add_loop_test(tc1_1, test_logLoop, 1, 200);
  tcase_add_loop_test(tc1_1, test_logMinus, -200, 0);
  tcase_add_test(tc1_1, test_logInf);
  tcase_add_test(tc1_1, test_logNan);
  tcase_add_loop_test(tc1_1, test_expLoop, -32, 200);
  tcase_add_test(tc1_1, test_expInf);
  tcase_add_test(tc1_1, test_expNan);
  tcase_add_test(tc1_1, test_abs);
  tcase_add_test(tc1_1, test_fabs);
  tcase_add_test(tc1_1, test_floor);
  tcase_add_test(tc1_1, test_ceil);
  tcase_add_test(tc1_1, test_pow);
  tcase_add_test(tc1_1, test_sqrt);
  tcase_add_test(tc1_1, test_fmod);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
